version: '3'
services: 
  flatris:
    build:
      context: ./
      dockerfile: dockerfile-flatris
    ports:
      - "3000:3000"
  clusmy-bird:
    build:
      context: ./ 
      dockerfile: dockerfile-clumsy-bird
    ports:
      - "8001:8001"
    expose:
      - "8001"
    entrypoint: grunt
    command: connect
